eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:6001/eureka
spring:
  cloud:
    gateway:
      routes:
        - id: microservice-GestionAbonnement
          uri: lb://microservice-GestionAbonnement
          predicates:
            - Path=/Abonnement/**
          filters:
            - RewritePath=/Abonnement /(?<path>.*), /$\\{path}
